const main = async function() {try {(await new Promise(o => {
try {{}} catch(error) {
}}));
(await new Promise(async (ok, fail) => {
try {{}} catch(error) {
}}));} catch(error) {
}};