const x = async function() {try {} catch(error) {
}};